evote/urls.py
from django.conf.urls import include
from django.contrib import admin
from django.urls import path
from . import views 
from django.contrib.staticfiles.urls import staticfiles_urlpatterns
from django.conf import settings
from django.conf.urls.static import static

urlpatterns = [
    path('admin/', admin.site.urls),
    path('', views.landing, name="landing_page"),
    path('dashboard/', include('dashboard.urls')),
    path('accounts/', include('accounts.urls')),
    path('officer/', include('officer.urls')),
]


urlpatterns += staticfiles_urlpatterns()
urlpatterns += static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

officer/urls.py
from django.urls import path
from . import views

app_name = 'officer'

urlpatterns = [
    path('', views.officer, name="officercrud"),
    path('candidates', views.candidate, name="cand"),
    path('users', views.realuser, name="user"),
    path('quaries', views.quaries, name="quary"),
    path('quariessolved/', views.quarysolved, name="quarysolved"),
    path('addcand/', views.add_candidate, name="addcand"),
    path('delcand/', views.delete_candidate, name="delcand"),
    path('editcand/<int:id>/', views.edit_candidate, name="editcand"),
    path('deluser/', views.delete_user, name="deluser"),
    path('edituser/<int:id>/', views.edit_user, name="edituser"),
    path('electionstarted/', views.start_election, name="startelection"),
    path('electionended/', views.end_election, name="endelection"),
]

officer/models.py
from django.db import models

class Election(models.Model):
    status = models.BooleanField(default=False)
    
    def __bool__(self):
        return self.status

officer/forms.py
from django import forms
from dashboard.models import Candidate
from django.contrib.auth.models import User

class AddCandidate(forms.ModelForm):
    class Meta:
        model = Candidate
        fields = ("name", "team", "slogan", "description")
        widgets = {
            'name':forms.TextInput(attrs={'class':'form-control'}),
            'team':forms.TextInput(attrs={'class':'form-control'}),
            'slogan':forms.TextInput(attrs={'class':'form-control'}),
            'description':forms.TextInput(attrs={'class':'form-control'})
        }

class AddUser(forms.ModelForm):
    class Meta:
        model = User
        fields = ("username","first_name","last_name","email")
        widgets = {
            'username':forms.TextInput(attrs={'class':'form-control'}),
            'first_name':forms.TextInput(attrs={'class':'form-control'}),
            'last_name':forms.TextInput(attrs={'class':'form-control'}),
            'email':forms.TextInput(attrs={'class':'form-control'})
           }

officer/views.py
from django.shortcuts import redirect, render, get_object_or_404
from accounts.models import Profile
from accounts.views import address_creation
from dashboard.models import *
from django.contrib.auth.models import User
from .forms import AddCandidate,AddUser
from .decorators import *
from dashboard.functions import add_Candidate
from .models import Election

# Create your views here.
@allowed_users(allowed_roles=['Admin', 'Staff'])
def officer(request):
    is_status = Election.objects.get(id=1)
    can_count = Candidate.objects.all().count()
    user_count = Profile.objects.all().count()
    quary_count = Feedback.objects.all().count()
    return render(request, 'officer/officer.html', {
        'cancount':can_count,
        'usercount':user_count,
        'quarycount':quary_count,
        'status': is_status.status
        })

@allowed_users(allowed_roles=['Admin', 'Staff'])
def candidate(request):
    can_data = Candidate.objects.all()
    return render(request, 'officer/candidate.html', {
        'candata':can_data
    })

@allowed_users(allowed_roles=['Admin', 'Staff'])
def add_candidate(request):
    fm = AddCandidate(request.POST)
    if fm.is_valid():
        fm.save()
        return redirect('/officer/candidates')
    else:
        return render(request, 'officer/add-candidate.html', {'form':fm})

@allowed_users(allowed_roles=['Admin', 'Staff'])
def delete_candidate(request):
    data = request.POST
    id = data.get('id')
    canddata = Candidate.objects.get(id=id)
    canddata.delete()
    return redirect('/officer/candidates')

# def edit_candidate(request, id):
#     cand = Candidate.objects.get(id=id)
#     fm = AddCandidate(request.POST)
#     return render(request, 'edit-candidate.html', {'form':fm})
#     if fm.is_valid():
#         fm.save()
#         return redirect('/officer')

@allowed_users(allowed_roles=['Admin', 'Staff'])
def edit_candidate(request, id):
    context ={}
    obj = get_object_or_404(Candidate, id = id)
    form = AddCandidate(request.POST or None, instance = obj)

    if form.is_valid():
        form.save()
        return redirect('/officer/candidates')

    context["form"] = form
    return render(request, "officer/edit-candidate.html", context)


# USER CRUD OPERATIONS
@allowed_users(allowed_roles=['Admin', 'Staff'])
def realuser(request):
    user_data = User.objects.all()
    return render(request, 'officer/user.html', {
        'userdata':user_data
    })

@allowed_users(allowed_roles=['Admin', 'Staff'])
def add_user(request):
    fm = AddUser(request.POST)
    if fm.is_valid():
        fm.save()
        return redirect('/officer/users')
    else:
        return render(request, 'officer/add-user.html', {'form':fm})

@allowed_users(allowed_roles=['Admin', 'Staff'])
def delete_user(request):
    data = request.POST
    id = data.get('id')
    userdata = User.objects.get(id=id)
    userdata.delete()
    return redirect('/officer/users')

@allowed_users(allowed_roles=['Admin', 'Staff'])
def edit_user(request, id):
    context ={}
    obj = get_object_or_404(User, id = id)
    form = AddUser(request.POST or None, instance = obj)

    if form.is_valid():
        form.save()
        return redirect('/officer/users')

    context["form"] = form
 
    return render(request, "officer/edit-user.html", context)

@allowed_users(allowed_roles=['Admin', 'Staff'])
def quaries(request):
    quaries_data = Feedback.objects.all()
    return render(request, 'officer/contact_res.html', {
        'quariesdata':quaries_data
    })

@allowed_users(allowed_roles=['Admin', 'Staff'])
def quarysolved(request):
    data = request.POST
    id = data.get('id')
    quariesdata = Feedback.objects.get(id=id)
    quariesdata.delete()
    return redirect('/officer/quaries')

@allowed_users(allowed_roles=['Admin', 'Staff'])
def Approved_candidate(request):
    print("Approving candidate...")
    candidate = Candidate.objects.all()
    add_Candidate(candidate)
    print("Candidate Approved...")

@allowed_users(allowed_roles=['Admin', 'Staff'])
def start_election(request):
    address_creation()
    Approved_candidate(request)
    return redirect('/officer/')

@allowed_users(allowed_roles=['Admin', 'Staff'])
def end_election(request):
    is_sts = Election.objects.get(id=1)
    is_sts.status = False
    is_sts.isCandidateAdded = False
    is_sts.save()
    return redirect('/officer/')

templates/officer/add-candidate.html
{% extends 'base.html' %}
{% load static %}

{% block content %}

<style>

    ul.errorlist {
        display:none;
        }

</style>

<section class="container">
<div class="row justify-content-around mt-3 text-center">
    <div class="col-sm-8">
        <h1> Add Candidate </h1>
    </div>
</div>

<div class="row justify-content-around">
    <div class="col-sm-6">
        <form action="" method="POST" class="bg-white p-3 rounded shadow">
            {% csrf_token %}
            {{form.as_p}}
            <input type="submit" value="Submit" class="btn btn-primary">
        </form>
    </div>
</div>

</section>

{% endblock content %}

templates/officer/add-user.html
{% extends 'base.html' %}
{% load static %}

{% block content %}

<style>

    ul.errorlist, .helptext {
        display:none;
        }

</style>

<section class="container">
<div class="row justify-content-around mt-3 text-center">
    <div class="col-sm-8">
        <h1> Add User </h1>
    </div>
</div>

<div class="row justify-content-around">
    <div class="col-sm-6">
        <form action="" method="POST" class="bg-white p-3 rounded shadow">
            {% csrf_token %}
            {{form.as_p}}
            <input type="submit" value="Submit" class="btn btn-primary">
        </form>
    </div>
</div>

</section>

{% endblock content %}

templates/officer/candidate.html
{% extends 'officer/officer_sidebar.html' %}
{% load static %}

{% block content %}

{% comment %} adding sidebar {% endcomment %}
 <link rel="stylesheet" href="{% static 'dashboard.css' %}">

<body>

<div class="sidebar">
  <a href="{% url 'officer:officercrud' %}">Officer Dash</a>
  <a href="{% url 'officer:cand' %}">Candidates</a>
  <a href="{% url 'officer:user' %}">Users</a>
  <a href="{% url 'officer:quary' %}">User Quaries</a>
</div> 
{% comment %} Finish sidebar {% endcomment %}

<section class="container">

<div class="row justify-content-around mt-3 text-center">
    <div class="col-sm-8">
        <h1> Candidates Data </h1>
    </div>
</div>

<div class="row justify-content-around">
    <div class="col-sm-10">
        <a href="{% url 'officer:addcand' %}" class="btn btn-primary float-right">Add Candidate</a>
    </div>
</div>

<div class="row justify-content-around mt-1 text-center">
    <div class="col-sm-10">
        <table class="table table-hover">
            <thead>
                <tr>
                    <th scope="col">ID</th>
                    <th scope="col">Name</th>
                    <th scope="col">Team</th>
                    <th scope="col">Slogan</th>
                    <th scope="col">Description</th>
                    <th scope="col">Action</th>
                </tr>
            </thead>
            <tbody>
            {% for cand in candata %}
                <tr>
                    <th scope="row">{{forloop.counter}}</th>
                    <td>{{cand.name}}</td>
                    <td>{{cand.team}}</td>
                    <td>{{cand.slogan}}</td>
                    <td>{{cand.description}}</td>
                    <td>
                        <form action={% url 'officer:delcand' %} method="POST">
                        {% csrf_token %}
                        <input type="hidden" name="id" value={{cand.id}}>
                        <input type="submit" value="Delete" class="btn-sm btn-danger">
                        </form>
                    </td>
                    <td>
                        {% comment %} <a href="{% url 'officer:editcand' cand.id %}" class="btn btn-sm btn-info">Edit</a> {% endcomment %}

                        <form action={% url 'officer:editcand' cand.id %}>
                        {% csrf_token %}
                        <input type="submit" value="Edit" class="btn-sm btn-info">
                        </form>
                    </td>
                </tr>
            {% endfor %}
            </tbody>
        </table>
    </div>
</div>


</br>
</br>
</br>
</br>
</br>
</br>
</section>

{% endblock content %}

templates/officer/comform.html
{% extends 'officer/officer.html' %}
{% load static %}

{% block content %}
    <p>Are you sure want to start Election ?</p>
    <a href="{% url 'officer/' %}">No</a>
    <a href="{% url 'officer:startelection' %}">Yes</a>
{% endblock%}

templates/officer/contact_res.html
{% extends 'officer/officer_sidebar.html' %}
{% load static %}

{% block content %}

{% comment %} adding sidebar {% endcomment %}
 <link rel="stylesheet" href="{% static 'dashboard.css' %}">

<body>

<div class="sidebar">
  <a href="{% url 'officer:officercrud' %}">Officer Dash</a>
  <a href="{% url 'officer:cand' %}">Candidates</a>
  <a href="{% url 'officer:user' %}">Users</a>
  <a href="{% url 'officer:quary' %}">User Quaries</a>
</div> 
{% comment %} Finish sidebar {% endcomment %}

<section class="container">

<div class="row justify-content-around mt-3 text-center">
    <div class="col-sm-8">
        <h1> Quaries Data </h1>
    </div>
</div>


<div class="row justify-content-around mt-1 text-center">
    <div class="col-sm-10">
        <table class="table table-hover">
            <thead>
                <tr>
                    <th scope="col">S.No</th>
                    <th scope="col">Name</th>
                    <th scope="col">Email</th>
                    <th scope="col">Subject</th>
                    <th scope="col">message</th>
                    <th scope="col">Date</th>
                    <th scope="col">Action</th>
                </tr>
            </thead>
            <tbody>
            {% for que in quariesdata %}
                <tr>
                    <th scope="row">{{forloop.counter}}</th>
                    <td>{{que.name}}</td>
                    <td>{{que.email}}</td>
                    <td>{{que.subject}}</td>
                    <td>{{que.message}}</td>
                    <td>{{que.date}}</td>
                    <td>
                        <form action={% url 'officer:quarysolved' %} method="POST">
                        {% csrf_token %}
                        <input type="hidden" name="id" value={{que.id}}>
                        <input type="submit" value="Solved" class="btn-sm btn-info">
                        </form>
                    </td>

                    <td>
                        {% comment %} <a href="{% url 'officer:editcand' cand.id %}" class="btn btn-sm btn-info">Edit</a> {% endcomment %}

                        {% comment %} <form action={% url 'officer:editcand' cand.id %}>
                        {% csrf_token %}
                        <input type="submit" value="Edit" class="btn-sm btn-info">
                        </form> {% endcomment %}
                    </td>
                </tr>
            {% endfor %}
            </tbody>
        </table>
    </div>
</div>


</br>
</br>
</br>
</br>
</br>
</br>
</section>

{% endblock content %}

templates/officer/edit-candidate.html
{% extends 'base.html' %}
{% load static %}

{% block content %}
<section class="container">
<div class="row justify-content-around mt-3 text-center">
    <div class="col-sm-8">
        <h1> Edit Candidate </h1>
    </div>
</div>

<div class="row justify-content-around">
    <div class="col-sm-6">
        <form action="" method="POST" class="bg-white p-3 rounded shadow">
            {% csrf_token %}
            {{form.as_p}}
            <input type="submit" value="Submit" class="btn btn-primary">
        </form>
    </div>
</div>

</section>

{% endblock content %}

templates/officer/edit-user.html
{% extends 'base.html' %}
{% load static %}

{% block content %}
<style>
    .helptext {
        display: none;
    }
</style>

<section class="container">
<div class="row justify-content-around mt-3 text-center">
    <div class="col-sm-8">
        <h1> Edit User </h1>
    </div>
</div>

<div class="row justify-content-around">
    <div class="col-sm-6">
        <form action="" method="POST" class="bg-white p-3 rounded shadow">
            {% csrf_token %}
            {{form.as_p}}
            <input type="submit" value="Submit" class="btn btn-primary">
        </form>
    </div>
</div>

</section>

{% endblock content %}

templates/officer/officer.html
{% extends 'officer/officer_sidebar.html' %}
{% load static %}

{% block content %}

{% comment %} adding sidebar {% endcomment %}
 <link rel="stylesheet" href="{% static 'dashboard.css' %}">

<body>

<div class="sidebar">
  <a href="{% url 'officer:officercrud' %}">Officer Dash</a>
  <a href="{% url 'officer:cand' %}">Candidates</a>
  <a href="{% url 'officer:user' %}">Users</a>
  <a href="{% url 'officer:quary' %}">User Quaries</a>
</div> 
{% comment %} Finish sidebar {% endcomment %}

<section class="container">

<div class="row justify-content-around mt-3 text-center">
    <div class="col-sm-8">
        <h1> Welcome Officer </h1>
        {% if status%}
          <h4 style="color:green;margin-bottom: 25px;text-decoration: underline;">Election Started</h4>
        {% else %}
          <h4 style="color:red;margin-bottom: 25px;text-decoration: underline;">Election Ended</h4>
        {%endif%}

    </div>
</div>

<div class="container shadow text-center ">
<h5> Total Users&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;: {{ usercount }} </h5>
<h5> Total Candidates&nbsp;&nbsp;&nbsp;&nbsp;: {{ cancount }} </h5>
<h5> User Quaries&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;: {{ quarycount }} </h5>
</div>
</br>
</br>

<div class="container row justify-content-center mt-3 text-center">
  <h3 class="mr-3"> Control the Election :</h3>
      {% if status%}
          <a href="{% url 'officer:endelection' %}" class="btn btn-danger" id="end" >End Election</a>
      {% else %}
          <a href="{% url 'officer:startelection' %}" class="btn btn-success" id="start" >Start Election</a>
      {%endif%}
</div>

</section>

{% endblock content %}

templates/officer/officer_sidebar.html
{% extends 'base.html' %}
{% load static %}

{% comment %} adding sidebar {% endcomment %}
<link rel="stylesheet" href="{% static 'dashboard.css' %}">
</head>
<body>


{% comment %} <div class="sidebar">
  <a href="#">Dashboard</a>
  <a href="#">Candidates</a>
  <a href="#">Users</a>
  <a href="#">Requests</a>
</div> {% endcomment %}


{% comment %} Finish sidebar {% endcomment %}

{% block content %}

{% endblock content %}

templates/officer/user.html
{% extends 'officer/officer_sidebar.html' %}
{% load static %}

{% block content %}

{% comment %} adding sidebar {% endcomment %}
 <link rel="stylesheet" href="{% static 'dashboard.css' %}">

<body>

<div class="sidebar">
  <a href="{% url 'officer:officercrud' %}">Officer Dash</a>
  <a href="{% url 'officer:cand' %}">Candidates</a>
  <a href="{% url 'officer:user' %}">Users</a>
  <a href="{% url 'officer:quary' %}">User Quaries</a>
</div> 
{% comment %} Finish sidebar {% endcomment %}

<section class="container">

<div class="row justify-content-around mt-3 text-center">
    <div class="col-sm-8">
        <h1> User Data </h1>
    </div>
</div>


{% comment %} CRUD for USER start here {% endcomment %}
{% comment %} <div class="row justify-content-around">
    <div class="col-sm-10">
        <a href="{% url 'officer:adduser' %}" class="btn btn-primary float-right">Add User</a>
    </div>
</div> {% endcomment %}

<div class="row justify-content-around mt-1 text-center">
    <div class="col-sm-10">
        <table class="table table-hovers">
        <thead>
            <tr>
                <th scope="col">S.no</th>
                <th scope="col">User</th>
                <th scope="col">Fname</th>
                <th scope="col">Lname</th>
                <th scope="col">Email</th>
                <th scope="col">Action</th>
            </tr>
        </thead>
        <tbody>
                {% for udata in userdata %}
            <tr>
                <th scope="row">{{forloop.counter}}</th>
                <td>{{udata.username}}</td>
                <td>{{udata.first_name}}</td>
                <td>{{udata.last_name}}</td>
                <td>{{udata.email}}</td>
                <td>
                    <form action={% url 'officer:deluser' %} method="POST">
                        {% csrf_token %}
                        <input type="hidden" name="id" value={{udata.id}}>
                        <input type="submit" value="Delete" class="btn btn-sm btn-danger">
                        </form>
                </td>
                <td>
                        {% comment %} <a href="{% url 'officer:editcand' cand.id %}" class="btn btn-sm btn-info">Edit</a> {% endcomment %}

                        <form action={% url 'officer:edituser' udata.id %}>
                        {% csrf_token %}
                        <input type="submit" value="Edit" class="btn-sm btn-info">
                        </form>
                    </td>
            </tr>
                {% endfor %}
        </tbody>
        </table>
    </div>
</div>
{% comment %} CRUD user end here {% endcomment %}
</br>
</br>
</br>
</br>
</br>
</br>
</section>

{% endblock content %}