accounts/urls.py
from django.urls import path
from . import views
# from django.conf import settings
# from django.conf.urls.static import static

app_name = 'accounts'

urlpatterns = [
    path('signup/', views.signup_view, name="signup"),
    path('login/', views.login_view, name="login"),
    path('logout/', views.logout_view, name="logout"),
    # path('submitvote/',views.submit_vote,name="submitvote")
] 

# + static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

dashboard/urls.py
from django.urls import path
from . import views

app_name = 'dashboard'

urlpatterns = [
    path('', views.dashboard, name="dash"),
    path('vote/', views.votes, name="vote"),
    path('<int:pk>/', views.Vote,name="Vote"),
    path('result/',views.Result,name="Result"),
    path('feedback/',views.Feedback,name="feedback"),
]

evote/urls.py
from django.conf.urls import include
from django.contrib import admin
from django.urls import path
from . import views 
from django.contrib.staticfiles.urls import staticfiles_urlpatterns
from django.conf import settings
from django.conf.urls.static import static

urlpatterns = [
    path('admin/', admin.site.urls),
    path('', views.landing, name="landing_page"),
    path('dashboard/', include('dashboard.urls')),
    path('accounts/', include('accounts.urls')),
    path('officer/', include('officer.urls')),
]


urlpatterns += staticfiles_urlpatterns()
urlpatterns += static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

officer/urls.py
from django.urls import path
from . import views

app_name = 'officer'

urlpatterns = [
    path('', views.officer, name="officercrud"),
    path('candidates', views.candidate, name="cand"),
    path('users', views.realuser, name="user"),
    path('quaries', views.quaries, name="quary"),
    path('quariessolved/', views.quarysolved, name="quarysolved"),
    path('addcand/', views.add_candidate, name="addcand"),
    path('delcand/', views.delete_candidate, name="delcand"),
    path('editcand/<int:id>/', views.edit_candidate, name="editcand"),
    path('deluser/', views.delete_user, name="deluser"),
    path('edituser/<int:id>/', views.edit_user, name="edituser"),
    path('electionstarted/', views.start_election, name="startelection"),
    path('electionended/', views.end_election, name="endelection"),
]

dashboard/models.py
from django.db import models


class Candidate(models.Model):
    name = models.CharField(max_length=100)
    team = models.CharField(max_length=100)
    slogan = models.CharField(max_length=200)
    description = models.TextField()

    def __str__(self):
        return self.name


class Feedback(models.Model):
    name = models.CharField(max_length=100)
    email = models.EmailField(max_length=200)
    subject = models.CharField(max_length=100)
    message = models.CharField(max_length=100)
    date = models.CharField(max_length=100)

    class Meta:
        verbose_name_plural = "Feedback"

    def __str__(self):
        return self.name + "-" + self.email

    

dashboard/forms.py
from django import forms
# from django.contrib.auth.models import User
from django.contrib.auth.forms import UserCreationForm
from django.template.defaultfilters import slugify
from .models import Feedback

class FeedbackForm(forms.ModelForm):

    class Meta:
        model = Feedback
        fields = '__all__'

dashboard/views.py
from django.shortcuts import render
from django.contrib.auth.decorators import login_required
from .models import Candidate
from . import functions
from django.contrib import messages
from .forms import FeedbackForm
from officer.models import Election
from accounts.models import Profile

voted = []

@login_required(login_url="/accounts/login")
def dashboard(request):
    return render(request, 'dashboard.html')

@login_required(login_url="/accounts/login")
def votes(request):
    is_sts = Election.objects.get(id=1)
    if is_sts.status==True:
        candidates = Candidate.objects.all()
        return render(request, 'vote.html',{'candidates': candidates})
    else:
        return render(request,'noVote.html')
    
# @login_required(login_url="/accounts/submitvote")
def Vote(request,pk):
    Voted_name = Candidate.objects.get(id=pk)
    user_token = Profile.objects.get(user=request.user)
    tok = user_token.token
    try:
        if ( tok in voted):
            return render(request, 'alreadyVoted.html')
        else:
            voted.append(tok)
            hashr = functions.Transactions(Voted_name,user_token.token)
            print(hashr)
            return render(request, 'Voted.html')
    except:
        return render(request, 'alreadyVoted.html')
    

def Result(request):
    is_sts = Election.objects.get(id=1)
    if (is_sts.status):
        return render(request,'noResult.html')
    else:
        try:
            result = functions.final_result()
        except:
            print('Error in results.')
            return render(request,'noResult.html')
        return render(request,'Result.html',{
                            'candidate': result['candidates'],
                            'result': result['result']
                            })
        
    


def Feedback(request):
    if request.method == 'POST':
        f = FeedbackForm(request.POST)
        if f.is_valid():
            f.save()
            messages.add_message(request, messages.INFO, 'Feedback Submitted.')
            return render(request, 'dashboard.html')

    else:
        f = FeedbackForm()
    return render(request, 'contact.html', {'form': f})

templates/Result.html
{% extends 'base_entry.html' %}
{% load static %}

{% block dash %}
<center>
    <h1> Results: </h1> 
    <div id="container" style="width: 50%;">
        <canvas id="pie-chart"></canvas>
      </div>
    
      <script src="https://cdn.jsdelivr.net/npm/chart.js@2.9.3/dist/Chart.min.js"></script>
      <script>
    
        var config = {
          type: 'pie',
          data: {
            datasets: [{
              data: {{ result|safe }},
              backgroundColor: [
                '#E1C340', '#4CD7D0', '#189AB4', '#D4F1F4', '#007bff'
              ],
              label: 'Population'
            }],
            labels: {{ candidate|safe }}
          },
          options: {
            responsive: true
          }
        };
    
        window.onload = function() {
          var ctx = document.getElementById('pie-chart').getContext('2d');
          window.myPie = new Chart(ctx, config);
        };
    
      </script>

</center>
{% endblock dash %}

templates/Voted.html
{% extends 'base_entry.html' %}
{% load static %}

{% block dash %}

<center><h1> You've successfully voted</h1> </center>
{% endblock dash %}

templates/alreadyVoted.html
{% extends 'base_entry.html' %}
{% load static %}

{% block dash %}

    <div class="container text-center mt-5">
        <h1> Sorry !!! (Voting interrupted) You have already voted! </h1>
        <h5> Please refer to query sections for further knowledge. </h5></br></br>
        <a href="{% url 'dashboard:feedback' %}" class="btn btn-info"> Query </a>
     </div>



{% endblock dash %}

templates/base.html
{% load static %}
<!doctype html>
<html lang="en">

<head>
    <link rel="stylesheet" href="https://stackpath.bootstrapcdn.com/bootstrap/4.4.1/css/bootstrap.min.css">
    <link rel="stylesheet" href="{% static 'style.css' %}">
    
    <title>eChunab | Cast your vote from anywhere</title>
</head>

<body>
    <div class="container">
        <header class="head my-3">
            <nav class="navbar navbar-expand-lg navbar-light head__custom-nav">
                <a class="navbar-brand d-flex align-items-center" href="{% url 'landing_page' %}">
                    <img src="{% static 'media/logo.png' %}" alt="website logo">
                </a>
                <button class="navbar-toggler" type="button" data-toggle="collapse" data-target="#navbarNav">
                    <span><img id="hamburger" src="{% static 'media/menu.png' %}" alt=""></span>
                </button>
                <div class="collapse navbar-collapse justify-content-end" id="navbarNav">
                    <ul class="navbar-nav">
                        <li class="nav-item">
                            <a class="nav-link" href="{% url 'landing_page' %}">Home</a>
                        </li>
                        <li class="nav-item">
                            <a class="nav-link" href="#">About us</a>
                        </li>
                        <li class="nav-item">
                            <a class="nav-link" href="#">Info</a>
                        </li>

                        {% load user_tags %}
                        {% if request.user|has_group:"Admin" %}
                        <li class="nav-item">
                            <a class="nav-link" href="{% url 'officer:officercrud' %}">Officer</a>
                        </li>
                        {% endif %}

                        {% if user.is_authenticated %}
                        <li class="nav-item">
                            <a class="nav-link text-primary" href="{% url 'accounts:logout' %}">Logout</a>
                        </li>
                        {% else %}
                        <li class="nav-item">
                            <a class="nav-link text-primary" href="{% url 'accounts:login' %}">Login/Signup</a>
                        </li>
                        {% endif %}
                        
                        
 
                    </ul>
                </div>
            </nav>
        </header>
        {% include 'messages.html' %}
    </div>

{% block content %}



{% endblock content %}    
<script>
    setTimeout(function(){
        if ($('.auto-close').length > 0) {
            $('.auto-close').remove();
        }
    }, 1500)
</script>
<script src="https://code.jquery.com/jquery-3.4.1.slim.min.js"></script>
<script src="https://cdn.jsdelivr.net/npm/popper.js@1.16.0/dist/umd/popper.min.js"></script>
<script src="https://stackpath.bootstrapcdn.com/bootstrap/4.4.1/js/bootstrap.min.js"></script>   
</body>
</html>

templates/base_entry.html
{% extends 'base.html' %}
{% load static %}
{% block content %}
    
<html>
<head>
<meta name="viewport" content="width=device-width, initial-scale=1.0">
<link rel="stylesheet" href="{% static 'dashboard.css' %}">
</head>
<body>

<div class="sidebar">
  <a href="{% url 'dashboard:dash' %}">Info</a>
  <a href="{% url 'dashboard:vote' %}">Vote Now</a>
  <a href="{% url 'dashboard:Result' %}">Results</a>
  <a href="{% url 'dashboard:feedback' %}">Submit Quary</a>
</div>

{% block dash %}



{% endblock dash %}

</body>
</html>


{% endblock content %}

templates/contact.html
{% extends 'base_entry.html' %}
{% load static %}

{% block dash %}

    {% if messages %}
    <ul class="messages">
        {% for message in messages %}
        <li{% if message.tags %} class="{{ message.tags }}"{% endif %}>{{ message }}</li>
        {% endfor %}
    </ul>
    {% endif %}

    <div class="container">
        <div class="row justify-content-around mt-5">
          <div class="col-sm-9">
               <h4><u>Send Quaries</u></h4></br>
               <form action="" method="post">
                    {% csrf_token %} 
                    <div class=form-group>
                         <label> Name: </label>
                         {{ form.name }}</br>
                         <label> Email: </label>
                         {{ form.email }}</br>
                         <label> Subject: </label>
                         {{ form.subject }}</br>
                         <label> Message: </label>
                         {{ form.message }}</br>
                         <label> Date: </label>
                         {{ form.date }}
                    </div>
                    <input type="submit" value="Send" class="btn btn-primary col-3">
               </form>
          </div>
        </div>
     </div>



{% endblock dash %}

templates/dashboard.html
{% extends 'base_entry.html' %}
{% load static %}

{% block dash %}    

<div class="content">
  <h2>Read the Guidelines</h2>
  <p>Please read these Guidelines beofre proceeding it'll be easy for you to use our webapp</p>
  <ol>
    <li>Ability to assure that only eligible voters are allowed/able to vote
- use of specific password & login security)
-current roster of eligible voters
-reasonable and announced period (eg. 2 weeks) for voting that is fairly consistent
across all voting if not specified in procedures; send reminder before voting period closes </li>
    <li>Anonymity v. confidentiality – if #1 is met, the vote can’t be anonymous. However, it can be
kept confidential by limiting the access to the identity of voters to a trusted source(s). For
example, for Senate elections we use Catalyst and only the Secretary of the Faculty & her
assistant have access to the uwnetids of voters and have confidentiality as part of their job
description..you could ask the ‘tellers’ to sign a confidentiality agreement if this is a concern. </li>
    <li>Actual voting setup issues (Catalyst allows this): a voter can change his own vote before it is
cast/”sent”; once “sent”, neither the voter nor anyone else can change the vote; a person can’t
vote more than once </li>
    <li>Documentation, Verification & Auditable – method to assure that a cast vote is really counted,
and can be recounted, if necessary; who voted, and who didn’t, as a public record; the voter can
discover if his vote has been changed (or miscounted) and fix it without destroying the secrecy
of the ballot</li>
    <li>Final vote is verified and certified by 2 people (eg. our votes are certified by the Secretary of
the Faculty & the Senate Chair) & reported in writing to the voters/official in charge
 </li>
  </ol>
</div>
{% endblock dash %}

templates/info.html
{% extends 'base.html' %}
{% load static %}

{% block content %}    
<style>

    .cont{
        padding-top: 50px;
        width: 80%;
        margin: auto;
        padding: auto;
    }

</style>

<div class="cont">
  <h2>Read the Guidelines</h2>
  <p>Please read these Guidelines beofre proceeding it'll be easy for you to use our webapp</p>
  <ol>
    <li>Ability to assure that only eligible voters are allowed/able to vote
        - use of specific password & login security)
        -current roster of eligible voters
        -reasonable and announced period (eg. 2 weeks) for voting that is fairly consistent
        across all voting if not specified in procedures; send reminder before voting period closes 
    </li>
    <li>Anonymity v. confidentiality – if #1 is met, the vote can’t be anonymous. However, it can be
        kept confidential by limiting the access to the identity of voters to a trusted source(s). For
        example, for Senate elections we use Catalyst and only the Secretary of the Faculty & her
        assistant have access to the uwnetids of voters and have confidentiality as part of their job
        description..you could ask the ‘tellers’ to sign a confidentiality agreement if this is a concern. 
    </li>
    <li>Actual voting setup issues (Catalyst allows this): a voter can change his own vote before it is
        cast/”sent”; once “sent”, neither the voter nor anyone else can change the vote; a person can’t
        vote more than once 
    </li>
    <li>Documentation, Verification & Auditable – method to assure that a cast vote is really counted,
        and can be recounted, if necessary; who voted, and who didn’t, as a public record; the voter can
        discover if his vote has been changed (or miscounted) and fix it without destroying the secrecy
        of the ballot
    </li>
    <li>Final vote is verified and certified by 2 people (eg. our votes are certified by the Secretary of
        the Faculty & the Senate Chair) & reported in writing to the voters/official in charge
    </li>
  </ol>
</div>

{% endblock content %}

templates/landing.html
{% extends 'base.html' %}
{% load static %}

{% block content %}
    <style>
        *{
            margin:0px;
            padding: 0px;
        }
        .flag{
            width:170px;
            height: 512px;
        }
    </style>
    <div class="container">
        <div class="row custom-section d-flex align-items-center">
            <div class="col-12 col-lg-4">
                <h2>Casting Vote</h2>
                <h3>Ever been easier</h3>
                <p>With online voting system you're every vote is safe and unhackable with blockchain technology</p>
                
                {% if user.is_authenticated %}
                    <a href="{% url 'dashboard:dash' %}" >VOTE NOW</a>
                {% else %}
                    <a href="{% url 'accounts:login' %}">VOTE NOW</a>
                {% endif %}
            </div>
            <div class="col-12 col-lg-8">
                <img class="flag" src="{% static 'media/flag.png' %}" alt="Team process banner">
            </div>
        </div>
    </div>
{% endblock content %}

templates/messages.html
{% for message in messages %}
<div class="auto-close container-fluid p-0 position-absolute" style="z-index: 1;">
    <div class="alert {{ message.tags }} alert-dismissible" role="alert" >
    <button type="button" class="close" data-dismiss="alert" aria-label="Close">
        <span aria-hidden="true">×</span>
    </button>
    {{ message }}
    </div>
</div>
{% endfor %}

templates/noResult.html
{% extends 'base_entry.html' %}
{% load static %}

{% block dash %}

    <div class="container text-center mt-5">
        <h1> Result hasn't been published yet. </h1>
        <h5> Please refer to following sections for further knowledge. </h5></br></br>
        <a href="{% url 'dashboard:dash' %}" class="btn btn-info"> Guideliness </a>
        <a href="{% url 'dashboard:dash' %}" class="btn btn-success"> About Us </a>
        <a href="{% url 'dashboard:vote' %}" class="btn btn-info"> Vote </a>
     </div>



{% endblock dash %}

templates/noVote.html
{% extends 'base_entry.html' %}
{% load static %}

{% block dash %}

    <div class="container text-center mt-5">
        <h1> Voting process hasn't been started yet. </h1>
        <h5> Please refer to following sections for further knowledge. </h5></br></br>
        <a href="{% url 'dashboard:dash' %}" class="btn btn-info"> Guideliness </a>
        <a href="{% url 'dashboard:dash' %}" class="btn btn-success"> About Us </a>
        <a href="{% url 'dashboard:Result' %}" class="btn btn-info"> Result </a>
     </div>



{% endblock dash %}

templates/res.html
{% extends 'base_entry.html' %}

{% block dash %}
<style>

    #special{
        display: inline-block;
        width: 30%;
        margin:auto;

    }
    #candidate{
        width: 49%;
        float: left;
        list-style-type: none;
    }
    #result{
        width: 40%;
        float: right;
        text-align: center;
        list-style-type: ':';
    }
    

</style>


<center>
<h1> Results: </h1> 
<ul id="special">
    <div id="candidate">
    {% for ram in candidates %}
    <li > {{ ram }}  </li>
    {% endfor %}
</div>
<div id="result">
    {% for key in result %}
    <li> {{ key }}  </li>
    {% endfor %}
</div>
</ul>
</center>

{% endblock dash %} 

templates/vote.html
{% extends 'base_entry.html' %}
{% load static %}

{% block dash %}

<style>
  
  .card-sep {
    box-shadow: 2px 5px 5px rgba(0, 0, 0, 0.19);
  }

  .img-sep {
    padding-top: 10px;
    border-radius: 50%;
    width: 120px;
    height: 120px;
    box-shadow: 0px 2px 0px 0px rgba(0, 0, 0, 0.19);
  }

</style>

<center><h3 class="vote-title"><u> Vote your favourite person </u></h3></center> 

{% for c in candidates %}
<center>
<div class="card card-sep " style="width: 15rem;">

  <div class="text-center">
    <img src="{% static 'media/ai.jpeg' %}" class="img-fluid img-sep" alt="...">
  </div>
  <div class="card-body">
    <h5 class="card-titl"> {{ c.name }} </h5>
    <small><i> {{ c.team }} </i></small>
    <p class="card-text"> {{ c.slogan }} </p>
    <a href="{% url 'dashboard:Vote' c.id %}">Vote now</a>
  </div>
</div>
</br>
</center>
{% endfor %}

{% endblock dash %}